import Link from "next/link";
import {
  ArrowRight,
  Bell,
  CalendarDays,
  Camera,
  Check,
  LayoutGrid,
  MapPin,
  MessageCircle,
  NotebookPen,
  ShoppingBasket,
  Sparkles,
  Sprout,
} from "lucide-react";
import { buildClimate } from "@/lib/garden/climate";
import { buildPlan, planContext } from "@/lib/garden/plan";
import { designWithRules } from "@/lib/garden/recommend";
import type { PlanInput } from "@/lib/garden/types";
import { fmtShort } from "@/lib/garden/dates";
import { GOALS } from "@/lib/garden/plants";
import { BedGrid } from "@/components/garden/visuals";
import { ButtonLink, Card, cx } from "@/components/ui";

// A real plan, generated by the same engine users get, for the hero preview.
function samplePlan() {
  const climate = buildClimate("20001", "7b", "DC", "estimate");
  const year = new Date().getFullYear() + 1;
  const input: PlanInput = {
    zip: "20001",
    climate,
    spaceType: "raised-bed",
    areas: [{ kind: "bed", id: "sample", name: "Raised bed", widthFt: 4, lengthFt: 8, raised: true }],
    bedsReady: true,
    sun: "full",
    goals: ["salsa", "salad"],
    wants: ["cherry-tomato", "basil"],
    notes: "",
    household: 2,
    experience: "new",
    time: "moderate",
    season: "spring",
    year,
  };
  const today = `${year - 1}-12-01`;
  const { ctx, evaluation } = planContext(input, today);
  return buildPlan(input, designWithRules(input, evaluation, ctx), today);
}

const FEATURES = [
  { icon: LayoutGrid, title: "A layout that fits", text: "Square-by-square bed plans with tall crops on the north side and proper spacing." },
  { icon: CalendarDays, title: "Your planting calendar", text: "When to start seeds, plant out and harvest, timed to your ZIP code's frost dates." },
  { icon: ShoppingBasket, title: "One shopping list", text: "Seeds, plants, soil and supplies with quantities and rough costs. No guesswork." },
  { icon: Bell, title: "Weekly reminders", text: "A short email each week with exactly what to do in your garden, and nothing else." },
  { icon: MessageCircle, title: "Ask Plantr", text: "Yellow leaves? Missed a date? Get answers that know your plants and your zone." },
  { icon: NotebookPen, title: "Harvest log", text: "Track what you picked and what worked, so next year's garden is even better." },
];

const FAQ = [
  {
    q: "Is Plantr free?",
    a: "Yes. Creating a plan is free and you don't need an account to start. Save it to My Garden (also free) to get weekly reminders and track tasks.",
  },
  {
    q: "I've never grown anything. Is this for me?",
    a: "That's exactly who it's for. Tell us you're new and we'll favor forgiving plants, buy-ready starts and a garden size you can actually keep up with.",
  },
  {
    q: "How do you know my frost dates?",
    a: "We find the NOAA weather station nearest your ZIP code and use its 30-year frost dates and temperatures. Know your exact local dates? You can adjust them.",
  },
  {
    q: "What if I only have a balcony or patio?",
    a: "Container gardens are fully supported. We pick compact varieties and tell you how many plants fit in each pot size.",
  },
  {
    q: "Can I grow indoors, on a windowsill?",
    a: "Yes. Choose Indoors and tell us which way your window faces, your pot size and whether you have a grow light. We'll pick herbs and greens that suit your light (and your pets), and give you a year-round sowing and care calendar.",
  },
  {
    q: "What happens to my photo?",
    a: "It's used to estimate your space's size and sunlight. We keep only a small thumbnail on your plan, never the original.",
  },
];

export default function Home() {
  const plan = samplePlan();
  const bed = plan.layouts[0];
  const upcoming = plan.tasks.filter((t) => t.category === "plant").slice(0, 3);

  return (
    <div className="overflow-x-clip">
      {/* Hero */}
      <section className="relative">
        <div className="absolute inset-x-0 top-0 -z-10 h-[620px] bg-gradient-to-b from-leaf-50 via-cream to-cream" />
        <div className="mx-auto grid max-w-6xl items-center gap-10 px-4 pb-16 pt-10 sm:pt-16 lg:grid-cols-[1.05fr_1fr] lg:gap-14 lg:pt-20">
          <div className="animate-rise">
            <p className="inline-flex items-center gap-2 rounded-full border border-leaf-200 bg-paper px-3 py-1 text-sm font-semibold text-leaf-700">
              <Sprout className="h-4 w-4" /> For first-time and casual gardeners
            </p>
            <h1 className="mt-5 font-display text-[44px] font-semibold leading-[1.05] tracking-tight sm:text-6xl">
              Your garden,
              <br />
              <span className="text-leaf-600">planned for you.</span>
            </h1>
            <p className="mt-5 max-w-xl text-lg leading-relaxed text-muted sm:text-xl">
              Take a photo of your space, tell us what you want to grow, and we&apos;ll tell you exactly what to plant, where to put it, and when to do
              it.
            </p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <ButtonLink href="/plan/new" size="lg">
                <Camera className="h-5 w-5" />
                Plan my garden. It&apos;s free
              </ButtonLink>
              <ButtonLink href="#how" size="lg" variant="secondary">
                How it works
              </ButtonLink>
            </div>
            <ul className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted">
              {["Takes about 2 minutes", "Timed to your ZIP code", "No account needed"].map((t) => (
                <li key={t} className="flex items-center gap-1.5">
                  <Check className="h-4 w-4 text-leaf-500" />
                  {t}
                </li>
              ))}
            </ul>
          </div>

          {/* Product preview */}
          <div className="relative mx-auto w-full max-w-md animate-rise [animation-delay:120ms] lg:max-w-none">
            <div className="absolute -right-6 -top-6 -z-10 h-40 w-40 rounded-full bg-sun-100 blur-2xl" />
            <Card className="overflow-hidden shadow-[var(--shadow-lift)]">
              <div className="flex items-center justify-between border-b border-line px-5 py-3.5">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-faint">Salsa & salad garden</p>
                  <p className="font-display text-lg font-semibold">4 × 8 ft raised bed · Zone 7b</p>
                </div>
                <span className="rounded-full bg-leaf-50 px-2.5 py-1 text-xs font-bold text-leaf-700">{plan.plants.length} crops</span>
              </div>
              <div className="bg-cream/50 px-3 pt-2">{bed?.kind === "bed" && <BedGrid layout={bed} raised selected={null} />}</div>
              <div className="flex flex-wrap gap-1.5 border-t border-line px-4 py-3">
                {plan.plants.slice(0, 6).map((p) => (
                  <span key={p.plantId} className="rounded-full bg-cream px-2.5 py-1 text-xs font-semibold">
                    {p.emoji} {p.name} ×{p.quantity}
                  </span>
                ))}
              </div>
              <div className="border-t border-line px-5 py-4">
                <p className="mb-2 text-xs font-bold uppercase tracking-wide text-leaf-600">Coming up</p>
                <ul className="space-y-2">
                  {upcoming.map((t) => (
                    <li key={t.id} className="flex items-center gap-3 text-sm">
                      <span className="w-14 shrink-0 font-semibold text-muted">{fmtShort(t.date)}</span>
                      <span className="font-medium">{t.title}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </Card>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="scroll-mt-20 border-y border-line bg-paper">
        <div className="mx-auto max-w-6xl px-4 py-16 sm:py-20">
          <p className="text-sm font-bold uppercase tracking-[0.14em] text-leaf-600">How it works</p>
          <h2 className="mt-2 max-w-2xl font-display text-4xl font-semibold leading-tight">From bare yard to a real plan in three steps</h2>
          <ol className="mt-10 grid gap-6 md:grid-cols-3">
            {[
              {
                icon: Camera,
                title: "Snap your space",
                text: "Take a photo of your yard, beds or balcony. We estimate the size and how much sun it gets. You confirm the details.",
              },
              {
                icon: MapPin,
                title: "Tell us what you love",
                text: "Salsa? Salads? Flowers for the bees? Pick your goals and favorite plants, and add your ZIP code for your local climate.",
              },
              {
                icon: Sparkles,
                title: "Get your garden plan",
                text: "A layout, planting calendar, shopping list and care schedule, all built for your space and your season.",
              },
            ].map((s, i) => (
              <li key={s.title} className="relative rounded-[var(--radius-card)] border border-line bg-cream/60 p-6">
                <span className="absolute right-5 top-4 font-display text-5xl font-semibold text-line-strong">{i + 1}</span>
                <span className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-leaf-600 text-white">
                  <s.icon className="h-6 w-6" />
                </span>
                <h3 className="mt-4 font-display text-xl font-semibold">{s.title}</h3>
                <p className="mt-2 leading-relaxed text-muted">{s.text}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:py-20">
        <p className="text-sm font-bold uppercase tracking-[0.14em] text-leaf-600">What you get</p>
        <h2 className="mt-2 max-w-2xl font-display text-4xl font-semibold leading-tight">Everything you need, nothing you don&apos;t</h2>
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f) => (
            <Card key={f.title} className="p-6">
              <f.icon className="h-6 w-6 text-leaf-600" />
              <h3 className="mt-3 font-display text-lg font-semibold">{f.title}</h3>
              <p className="mt-1.5 leading-relaxed text-muted">{f.text}</p>
            </Card>
          ))}
        </div>
      </section>

      {/* Ideas */}
      <section className="border-y border-line bg-leaf-800 text-white">
        <div className="mx-auto max-w-6xl px-4 py-16">
          <h2 className="font-display text-3xl font-semibold sm:text-4xl">Not sure where to start?</h2>
          <p className="mt-2 max-w-xl text-leaf-100">
            Pick a garden that sounds fun. We&apos;ll tailor it to your space and climate. Or{" "}
            <Link href="/explore" className="font-semibold text-white underline underline-offset-4">
              see what other gardeners are growing
            </Link>
            .
          </p>
          <div className="mt-8 flex flex-wrap gap-2.5">
            {GOALS.map((g) => (
              <Link
                key={g.id}
                href={`/plan/new?goal=${g.id}`}
                className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2.5 font-semibold ring-1 ring-white/20 transition-colors hover:bg-white/20"
              >
                <span aria-hidden>{g.emoji}</span>
                {g.label}
              </Link>
            ))}
            <Link
              href="/plan/new?space=indoor&goal=herbs"
              className="inline-flex items-center gap-2 rounded-full bg-sun-400 px-4 py-2.5 font-semibold text-ink transition-colors hover:bg-sun-300"
            >
              <span aria-hidden>🪟</span>
              Windowsill herbs
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-3xl px-4 py-16 sm:py-20">
        <h2 className="text-center font-display text-4xl font-semibold">Questions, answered</h2>
        <div className="mt-8 divide-y divide-line rounded-[var(--radius-card)] border border-line bg-paper">
          {FAQ.map((f) => (
            <details key={f.q} className="group px-5 py-4">
              <summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold">
                {f.q}
                <span className="text-xl text-leaf-600 transition-transform group-open:rotate-45" aria-hidden>
                  +
                </span>
              </summary>
              <p className="mt-2 leading-relaxed text-muted">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* Final CTA */}
      <section className="px-4 pb-20">
        <div className={cx("mx-auto max-w-4xl rounded-[2rem] bg-gradient-to-br from-leaf-600 to-leaf-800 px-6 py-12 text-center text-white sm:px-12")}>
          <h2 className="font-display text-3xl font-semibold sm:text-4xl">This could be your best garden yet</h2>
          <p className="mx-auto mt-3 max-w-lg text-leaf-100">Two minutes now saves a season of guesswork. Start with a photo, or just your ZIP code.</p>
          <ButtonLink href="/plan/new" size="lg" variant="sun" className="mt-8">
            Start my plan <ArrowRight className="h-5 w-5" />
          </ButtonLink>
        </div>
      </section>
    </div>
  );
}
