import type { Goal, Plant } from "./types";

// Curated, deterministic horticultural data for common U.S. home-garden plants.
// Timing is expressed relative to the average last spring frost so it works in every zone.
// Sources: Cooperative Extension planting guides and square-foot-gardening spacing conventions.

type Def = Omit<Plant, "companions" | "avoid" | "goals" | "tips" | "varieties"> &
  Partial<Pick<Plant, "companions" | "avoid" | "goals" | "tips" | "varieties">>;

function plant(def: Def): Plant {
  return {
    companions: [],
    avoid: [],
    goals: [],
    tips: [],
    varieties: [],
    ...def,
  };
}

export const PLANTS: Plant[] = [
  // ---------- Warm-season fruiting crops ----------
  plant({
    id: "tomato",
    name: "Tomato",
    emoji: "🍅",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 0.25,
    heightIn: 72,
    support: "cage",
    pot: { gal: 10, plants: 1 },
    dtm: 75,
    harvestWeeks: 10,
    method: "transplant",
    indoorWeeks: 7,
    plantOutWeeks: 2,
    buyStarts: true,
    difficulty: 2,
    water: "high",
    feeder: "heavy",
    companions: ["basil", "marigold", "carrot", "parsley", "chives", "nasturtium"],
    avoid: ["potato", "sweet-corn", "broccoli", "cabbage", "dill"],
    goals: ["salsa", "pizza", "salad", "preserving"],
    perPerson: 1,
    yield: "10–15 lb per plant over the season",
    varieties: ["Celebrity", "Better Boy", "Early Girl"],
    tips: [
      "Plant deep: bury the stem up to the first set of leaves. It roots all along the buried stem.",
      "Water deeply at the base 1–2 times a week. Uneven watering causes blossom-end rot and cracking.",
      "Mulch once the soil is warm to keep moisture steady and stop soil splashing disease onto leaves.",
    ],
    seedCost: 4,
    startCost: 5,
  }),
  plant({
    id: "cherry-tomato",
    name: "Cherry tomato",
    emoji: "🍅",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 0.25,
    heightIn: 72,
    support: "cage",
    pot: { gal: 5, plants: 1 },
    dtm: 60,
    harvestWeeks: 12,
    method: "transplant",
    indoorWeeks: 7,
    plantOutWeeks: 2,
    buyStarts: true,
    difficulty: 1,
    water: "high",
    feeder: "heavy",
    companions: ["basil", "marigold", "carrot", "parsley", "chives", "nasturtium"],
    avoid: ["potato", "sweet-corn", "broccoli", "cabbage", "dill"],
    goals: ["salad", "kids", "salsa"],
    perPerson: 1,
    yield: "Hundreds of bite-size tomatoes per plant",
    varieties: ["Sungold", "Sweet Million", "Juliet"],
    tips: [
      "The easiest tomato for beginners. It ripens weeks before big slicers.",
      "Pick when fully colored; split fruit after heavy rain is normal, so harvest before storms.",
      "Tie the main stems to the cage as they grow; plants easily reach 6 ft.",
    ],
    seedCost: 4,
    startCost: 5,
  }),
  plant({
    id: "paste-tomato",
    name: "Paste tomato",
    emoji: "🍅",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 0.25,
    heightIn: 48,
    support: "cage",
    pot: { gal: 10, plants: 1 },
    dtm: 75,
    harvestWeeks: 5,
    method: "transplant",
    indoorWeeks: 7,
    plantOutWeeks: 2,
    buyStarts: true,
    difficulty: 2,
    water: "high",
    feeder: "heavy",
    companions: ["basil", "marigold", "carrot", "parsley", "chives"],
    avoid: ["potato", "sweet-corn", "broccoli", "cabbage", "dill"],
    goals: ["salsa", "pizza", "preserving"],
    perPerson: 2,
    yield: "Most fruit ripens within a few weeks, ideal for sauce",
    varieties: ["Roma", "San Marzano", "Amish Paste"],
    tips: [
      "Meaty with few seeds: the best tomato for sauce, salsa and canning.",
      "Determinate types ripen in one big flush, so plan a sauce weekend.",
      "Keep watering even to prevent blossom-end rot, which paste types are prone to.",
    ],
    seedCost: 4,
    startCost: 5,
  }),
  plant({
    id: "bell-pepper",
    name: "Bell pepper",
    emoji: "🫑",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1,
    heightIn: 24,
    support: "stake",
    pot: { gal: 5, plants: 1 },
    dtm: 70,
    harvestWeeks: 10,
    method: "transplant",
    indoorWeeks: 9,
    plantOutWeeks: 3,
    buyStarts: true,
    difficulty: 2,
    water: "medium",
    feeder: "medium",
    companions: ["basil", "scallions", "carrot", "tomato", "okra"],
    goals: ["salsa", "pizza", "salad"],
    perPerson: 1,
    yield: "6–10 peppers per plant",
    varieties: ["California Wonder", "King of the North", "Ace"],
    tips: [
      "Peppers love heat. Wait until nights stay above 55°F before planting.",
      "Leave some on the plant to ripen red or yellow. They get much sweeter (allow 2–3 extra weeks).",
      "Cut peppers off with snips rather than pulling; the branches snap easily.",
    ],
    seedCost: 4,
    startCost: 5,
  }),
  plant({
    id: "hot-pepper",
    name: "Hot pepper",
    emoji: "🌶️",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1,
    heightIn: 30,
    pot: { gal: 3, plants: 1 },
    dtm: 70,
    harvestWeeks: 10,
    method: "transplant",
    indoorWeeks: 9,
    plantOutWeeks: 3,
    buyStarts: true,
    difficulty: 1,
    water: "medium",
    feeder: "medium",
    companions: ["basil", "scallions", "carrot", "tomato", "cilantro"],
    goals: ["salsa", "preserving"],
    perPerson: 0.5,
    yield: "25–50 peppers per plant",
    varieties: ["Jalapeño M", "Serrano", "Cayenne"],
    tips: [
      "Very productive. One or two plants keep most households in salsa.",
      "Heat builds as peppers mature; red jalapeños are hotter and sweeter than green.",
      "Wear gloves when handling the hottest varieties.",
    ],
    seedCost: 4,
    startCost: 5,
  }),
  plant({
    id: "eggplant",
    name: "Eggplant",
    emoji: "🍆",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1,
    heightIn: 30,
    support: "stake",
    pot: { gal: 5, plants: 1 },
    dtm: 70,
    harvestWeeks: 8,
    method: "transplant",
    indoorWeeks: 9,
    plantOutWeeks: 3,
    buyStarts: true,
    difficulty: 2,
    water: "medium",
    feeder: "heavy",
    companions: ["bush-beans", "marigold", "basil", "thyme"],
    avoid: ["potato"],
    goals: ["preserving"],
    perPerson: 0.5,
    yield: "4–8 large or 15+ small fruits per plant",
    varieties: ["Black Beauty", "Fairy Tale", "Ichiban"],
    tips: [
      "Flea beetles love young eggplant. Cover with row cover until the first flowers appear.",
      "Harvest while the skin is glossy; dull skin means overripe, seedy fruit.",
      "Compact varieties like Fairy Tale thrive in containers.",
    ],
    seedCost: 4,
    startCost: 5,
  }),
  plant({
    id: "cucumber",
    name: "Cucumber",
    emoji: "🥒",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 2,
    heightIn: 72,
    support: "trellis",
    pot: { gal: 5, plants: 1 },
    dtm: 55,
    harvestWeeks: 6,
    method: "direct",
    plantOutWeeks: 2,
    difficulty: 1,
    water: "high",
    feeder: "medium",
    companions: ["bush-beans", "pole-beans", "snap-peas", "radish", "dill", "nasturtium", "marigold", "sunflower"],
    avoid: ["potato", "sage"],
    goals: ["salad", "kids", "preserving"],
    perPerson: 1,
    yield: "10–20 cucumbers per plant",
    varieties: ["Marketmore 76", "Diva", "Spacemaster"],
    tips: [
      "Grow up a trellis: straighter fruit, fewer diseases and far less space.",
      "Pick every 1–2 days at peak. Oversized cucumbers turn bitter and slow the plant down.",
      "Water at the base in the morning to prevent powdery mildew.",
    ],
    seedCost: 3.5,
    startCost: 4.5,
  }),
  plant({
    id: "zucchini",
    name: "Zucchini",
    emoji: "🥒",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 0.25,
    heightIn: 30,
    support: "stake",
    pot: { gal: 10, plants: 1 },
    dtm: 50,
    harvestWeeks: 8,
    method: "direct",
    plantOutWeeks: 2,
    difficulty: 1,
    water: "high",
    feeder: "heavy",
    companions: ["nasturtium", "marigold", "radish", "sweet-corn", "pole-beans", "zinnia"],
    avoid: ["potato"],
    goals: ["kids"],
    perPerson: 0.34,
    yield: "6–10 lb per plant; one plant feeds a family",
    varieties: ["Black Beauty", "Eight Ball", "Astia"],
    tips: [
      "One or two plants is plenty. Zucchini is famously productive.",
      "Pick at 6–8 inches; they can double in size overnight.",
      "Check leaf undersides weekly for squash bug eggs (bronze clusters) and scrape them off.",
    ],
    seedCost: 3.5,
    startCost: 4.5,
  }),
  plant({
    id: "winter-squash",
    name: "Winter squash",
    emoji: "🎃",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1 / 9,
    heightIn: 24,
    pot: null,
    dtm: 100,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: 2,
    difficulty: 2,
    water: "medium",
    feeder: "heavy",
    companions: ["sweet-corn", "pole-beans", "nasturtium", "marigold", "radish"],
    avoid: ["potato"],
    goals: ["preserving"],
    perPerson: 0.5,
    yield: "4–8 squash per plant; stores 3–6 months",
    varieties: ["Waltham Butternut", "Honeynut", "Delicata"],
    tips: [
      "Vines sprawl 10+ ft. Let them run off the edge of the bed or over the lawn.",
      "Harvest when you can't dent the rind with a fingernail, then cure 10 days somewhere warm.",
      "Honeynut and Delicata are compact choices for small gardens.",
    ],
    seedCost: 3.5,
    startCost: 4.5,
  }),
  plant({
    id: "pumpkin",
    name: "Pumpkin",
    emoji: "🎃",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1 / 9,
    heightIn: 24,
    pot: null,
    dtm: 100,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: 2,
    difficulty: 2,
    water: "high",
    feeder: "heavy",
    companions: ["sweet-corn", "pole-beans", "nasturtium", "marigold", "radish"],
    avoid: ["potato"],
    goals: ["kids"],
    perPerson: 0.34,
    yield: "2–5 pumpkins per plant",
    varieties: ["Small Sugar", "Jack Be Little", "Howden"],
    tips: [
      "For Halloween pumpkins, count back about 110 days from early October to plant.",
      "Slip cardboard under developing pumpkins to prevent rot and flat spots.",
      "Leave 3–4 inches of stem when you cut them; they store much longer.",
    ],
    seedCost: 3.5,
    startCost: 4.5,
  }),
  plant({
    id: "cantaloupe",
    name: "Cantaloupe",
    emoji: "🍈",
    category: "fruit",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1 / 9,
    heightIn: 18,
    pot: null,
    dtm: 85,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: 3,
    difficulty: 3,
    water: "medium",
    feeder: "medium",
    companions: ["nasturtium", "marigold", "radish", "sweet-corn"],
    avoid: ["potato"],
    goals: ["kids"],
    perPerson: 0.5,
    yield: "3–5 melons per plant",
    varieties: ["Minnesota Midget", "Hale's Best Jumbo", "Ambrosia"],
    tips: [
      "Needs a long, hot summer. Choose Minnesota Midget if your season is short.",
      "A ripe cantaloupe 'slips' off the vine with a gentle push and smells sweet at the stem.",
      "Cut back on water as fruit ripens for sweeter melons.",
    ],
    seedCost: 4,
    startCost: 5,
  }),
  plant({
    id: "watermelon",
    name: "Watermelon",
    emoji: "🍉",
    category: "fruit",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1 / 9,
    heightIn: 18,
    pot: null,
    dtm: 80,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: 3,
    difficulty: 2,
    water: "medium",
    feeder: "medium",
    companions: ["nasturtium", "marigold", "radish", "sweet-corn"],
    avoid: ["potato"],
    goals: ["kids"],
    perPerson: 0.5,
    yield: "2–4 melons per plant",
    varieties: ["Sugar Baby", "Crimson Sweet", "Blacktail Mountain"],
    tips: [
      "'Icebox' types like Sugar Baby (8–10 lb) fit smaller gardens and shorter summers.",
      "Ripe when the curly tendril nearest the fruit turns brown and the ground spot turns creamy yellow.",
      "Set fruit on straw or cardboard to keep it off damp soil.",
    ],
    seedCost: 4,
    startCost: 5,
  }),
  plant({
    id: "bush-beans",
    name: "Bush beans",
    emoji: "🫘",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 9,
    heightIn: 18,
    pot: { gal: 3, plants: 4 },
    dtm: 55,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: 2,
    succession: 3,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["cucumber", "carrot", "sweet-corn", "marigold", "radish", "strawberry", "potato", "eggplant"],
    avoid: ["scallions", "garlic", "chives"],
    goals: ["kids", "low-maintenance", "preserving"],
    perPerson: 9,
    yield: "About ½ lb per square foot per sowing",
    varieties: ["Provider", "Blue Lake 274", "Contender"],
    tips: [
      "Sow a new square every 3 weeks until midsummer for a steady supply.",
      "Pick pods pencil-thin, before the beans bulge. Frequent picking keeps plants producing.",
      "Avoid working among beans when the leaves are wet; it spreads disease.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "pole-beans",
    name: "Pole beans",
    emoji: "🫘",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 8,
    heightIn: 84,
    support: "trellis",
    pot: { gal: 5, plants: 3 },
    dtm: 65,
    harvestWeeks: 8,
    method: "direct",
    plantOutWeeks: 2,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["sweet-corn", "cucumber", "winter-squash", "radish", "carrot", "pumpkin"],
    avoid: ["scallions", "garlic", "chives", "beet"],
    goals: ["low-maintenance", "preserving", "kids"],
    perPerson: 4,
    yield: "Up to 1 lb per plant over 6–8 weeks",
    varieties: ["Kentucky Wonder", "Blue Lake Pole", "Fortex"],
    tips: [
      "Put up a 6–7 ft trellis before you sow.",
      "Keep picking every few days and they'll produce until frost.",
      "Grow them on the north side so they don't shade shorter crops.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "sweet-corn",
    name: "Sweet corn",
    emoji: "🌽",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 4,
    heightIn: 84,
    pot: null,
    dtm: 80,
    harvestWeeks: 2,
    method: "direct",
    plantOutWeeks: 2,
    difficulty: 2,
    water: "high",
    feeder: "heavy",
    companions: ["pole-beans", "winter-squash", "pumpkin", "cucumber", "cantaloupe", "watermelon", "zucchini"],
    avoid: ["tomato", "cherry-tomato", "paste-tomato"],
    goals: ["kids"],
    perPerson: 8,
    yield: "1–2 ears per stalk",
    varieties: ["Bodacious", "Peaches and Cream", "Ambrosia"],
    tips: [
      "Plant in a block of at least 4×4, not a single row; corn is wind-pollinated.",
      "Ready about 20 days after silks appear, when silks are brown and kernels squirt milky juice.",
      "A big space-and-water investment for a modest harvest. Best for larger gardens.",
    ],
    seedCost: 4,
    startCost: 4.5,
  }),
  plant({
    id: "okra",
    name: "Okra",
    emoji: "🌱",
    category: "vegetable",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1,
    heightIn: 60,
    pot: { gal: 5, plants: 1 },
    dtm: 60,
    harvestWeeks: 10,
    method: "direct",
    plantOutWeeks: 4,
    difficulty: 1,
    water: "low",
    feeder: "medium",
    companions: ["bell-pepper", "hot-pepper", "cucumber", "cantaloupe", "basil"],
    goals: ["low-maintenance", "preserving"],
    perPerson: 1,
    yield: "A pod or two per plant every day in midsummer",
    varieties: ["Clemson Spineless", "Burgundy", "Jambalaya"],
    tips: [
      "Loves heat. A star in Southern gardens when other crops wilt.",
      "Harvest pods at 2–4 inches every day or two; big pods turn woody.",
      "Wear gloves and long sleeves when harvesting; the leaves can irritate skin.",
    ],
    seedCost: 3.5,
    startCost: 4.5,
  }),

  // ---------- Cool-season crops ----------
  plant({
    id: "lettuce",
    name: "Lettuce",
    emoji: "🥗",
    category: "vegetable",
    season: "cool",
    frost: "half-hardy",
    sun: "partial",
    perSqFt: 4,
    heightIn: 8,
    pot: { gal: 2, plants: 2 },
    dtm: 45,
    harvestWeeks: 4,
    method: "direct",
    plantOutWeeks: -4,
    fall: true,
    succession: 2,
    difficulty: 1,
    water: "high",
    feeder: "light",
    companions: ["carrot", "radish", "chives", "scallions", "strawberry", "cucumber", "calendula"],
    goals: ["salad", "kids"],
    perPerson: 4,
    yield: "Cut-and-come-again leaves for 4+ weeks",
    varieties: ["Salad Bowl", "Buttercrunch", "Black Seeded Simpson", "Red Sails"],
    tips: [
      "Harvest outer leaves and let the center keep growing.",
      "Bolts (turns bitter) in heat. Plant early, give afternoon shade, use heat-tolerant varieties in summer.",
      "Sow a few seeds every 2 weeks instead of all at once.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "spinach",
    name: "Spinach",
    emoji: "🍃",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 9,
    heightIn: 8,
    pot: { gal: 2, plants: 4 },
    dtm: 40,
    harvestWeeks: 4,
    method: "direct",
    plantOutWeeks: -6,
    fall: true,
    succession: 3,
    difficulty: 1,
    water: "medium",
    feeder: "medium",
    companions: ["strawberry", "radish", "snap-peas", "lettuce"],
    goals: ["salad", "cooking-greens"],
    perPerson: 9,
    yield: "About ¼ lb per square foot",
    varieties: ["Bloomsdale", "Space", "Corvair"],
    tips: [
      "One of the first crops you can plant. It shrugs off frost and even light snow.",
      "Bolts fast once days get long and hot, so plant early and again in late summer.",
      "Pick the largest outer leaves first.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "kale",
    name: "Kale",
    emoji: "🥬",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 1,
    heightIn: 24,
    pot: { gal: 3, plants: 1 },
    dtm: 55,
    harvestWeeks: 12,
    method: "transplant",
    indoorWeeks: 8,
    plantOutWeeks: -3,
    fall: true,
    buyStarts: true,
    difficulty: 1,
    water: "medium",
    feeder: "medium",
    companions: ["beet", "scallions", "dill", "nasturtium", "potato", "calendula"],
    avoid: ["strawberry", "tomato", "cherry-tomato", "paste-tomato"],
    goals: ["cooking-greens", "salad", "low-maintenance"],
    perPerson: 1,
    yield: "A handful of leaves per plant each week for months",
    varieties: ["Lacinato (Dinosaur)", "Winterbor", "Red Russian"],
    tips: [
      "Harvest lower leaves and let the top keep growing. One plant produces for months.",
      "Frost makes kale sweeter, and it often survives well into winter.",
      "Check under leaves for green cabbage worms; hand-pick them or use Bt.",
    ],
    seedCost: 3.5,
    startCost: 4.5,
  }),
  plant({
    id: "swiss-chard",
    name: "Swiss chard",
    emoji: "🥬",
    category: "vegetable",
    season: "cool",
    frost: "half-hardy",
    sun: "partial",
    perSqFt: 4,
    heightIn: 18,
    pot: { gal: 2, plants: 1 },
    dtm: 55,
    harvestWeeks: 16,
    method: "direct",
    plantOutWeeks: -2,
    fall: true,
    difficulty: 1,
    water: "medium",
    feeder: "medium",
    companions: ["bush-beans", "scallions", "cabbage", "lettuce"],
    goals: ["cooking-greens", "low-maintenance"],
    perPerson: 2,
    yield: "Harvest all season from a single planting",
    varieties: ["Bright Lights", "Fordhook Giant", "Peppermint"],
    tips: [
      "Cut outer stalks at the base. Plants keep producing from spring until hard frost.",
      "Handles summer heat far better than spinach: a great all-season green.",
      "Each 'seed' is a cluster, so thin to one seedling per spot.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "arugula",
    name: "Arugula",
    emoji: "🌿",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 9,
    heightIn: 8,
    pot: { gal: 1, plants: 6 },
    dtm: 35,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: -5,
    fall: true,
    succession: 2,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["lettuce", "spinach", "bush-beans", "beet"],
    goals: ["salad", "pizza"],
    perPerson: 4,
    yield: "Baby leaves in about a month",
    varieties: ["Astro", "Rocket", "Wild Rocket (Sylvetta)"],
    tips: [
      "Harvest young leaves; flavor gets spicier as it matures or the weather warms.",
      "Sow small amounts every 2 weeks in spring and fall.",
      "Flea beetles leave tiny holes. Row cover keeps leaves pristine.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "radish",
    name: "Radish",
    emoji: "🌱",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 16,
    heightIn: 6,
    pot: { gal: 1, plants: 8 },
    dtm: 28,
    harvestWeeks: 2,
    method: "direct",
    plantOutWeeks: -5,
    fall: true,
    succession: 2,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["carrot", "lettuce", "cucumber", "snap-peas", "spinach", "bush-beans"],
    goals: ["kids", "salad"],
    perPerson: 8,
    yield: "Ready in under a month",
    varieties: ["Cherry Belle", "French Breakfast", "Easter Egg"],
    tips: [
      "The fastest crop in the garden. Perfect for kids and impatient gardeners.",
      "Thin to 2 inches apart or they won't form roots.",
      "Harvest promptly; left too long they turn woody and extra spicy.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "carrot",
    name: "Carrot",
    emoji: "🥕",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 16,
    heightIn: 12,
    pot: { gal: 3, plants: 12 },
    dtm: 70,
    harvestWeeks: 4,
    method: "direct",
    plantOutWeeks: -3,
    fall: true,
    difficulty: 2,
    water: "medium",
    feeder: "light",
    companions: ["tomato", "cherry-tomato", "lettuce", "radish", "scallions", "chives", "snap-peas"],
    avoid: ["dill"],
    goals: ["kids", "salad"],
    perPerson: 16,
    yield: "16 carrots per square foot",
    varieties: ["Nantes", "Danvers", "Paris Market"],
    tips: [
      "Keep the seedbed constantly moist until sprouts appear (1–3 weeks). A board or burlap over the row helps.",
      "Thin to 2–3 inches apart; crowded carrots stay tiny.",
      "Loose, rock-free soil grows straight carrots. Use short varieties in clay or containers.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "beet",
    name: "Beet",
    emoji: "🌱",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 9,
    heightIn: 12,
    pot: { gal: 2, plants: 4 },
    dtm: 55,
    harvestWeeks: 4,
    method: "direct",
    plantOutWeeks: -3,
    fall: true,
    difficulty: 1,
    water: "medium",
    feeder: "medium",
    companions: ["lettuce", "scallions", "cabbage", "kale", "bush-beans"],
    avoid: ["pole-beans"],
    goals: ["salad", "cooking-greens", "preserving"],
    perPerson: 9,
    yield: "Sweet roots plus edible greens",
    varieties: ["Detroit Dark Red", "Chioggia", "Touchstone Gold"],
    tips: [
      "Each seed is a cluster. Thin seedlings to 3 inches apart and eat the thinnings.",
      "Harvest at golf-ball to tennis-ball size for the most tender roots.",
      "Soak seeds overnight before planting to speed germination.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "snap-peas",
    name: "Snap peas",
    emoji: "🫛",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "full",
    perSqFt: 8,
    heightIn: 60,
    support: "trellis",
    pot: { gal: 3, plants: 6 },
    dtm: 60,
    harvestWeeks: 4,
    method: "direct",
    plantOutWeeks: -6,
    fall: true,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["carrot", "radish", "cucumber", "spinach", "lettuce", "mint"],
    avoid: ["scallions", "garlic", "chives"],
    goals: ["kids", "salad"],
    perPerson: 8,
    yield: "Sweet, crunchy pods for 3–4 weeks",
    varieties: ["Sugar Snap", "Sugar Ann", "Super Sugar Snap"],
    tips: [
      "Plant as soon as the soil can be worked. Peas like it cool and quit in summer heat.",
      "Give them a 5–6 ft trellis or netting at planting time.",
      "Pick every 2 days; the more you pick, the more you get.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "broccoli",
    name: "Broccoli",
    emoji: "🥦",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "full",
    perSqFt: 1,
    heightIn: 30,
    pot: { gal: 5, plants: 1 },
    dtm: 60,
    harvestWeeks: 4,
    method: "transplant",
    indoorWeeks: 8,
    plantOutWeeks: -2,
    fall: true,
    buyStarts: true,
    difficulty: 2,
    water: "medium",
    feeder: "heavy",
    companions: ["dill", "scallions", "chives", "beet", "lettuce", "nasturtium", "calendula"],
    avoid: ["tomato", "cherry-tomato", "paste-tomato", "strawberry"],
    goals: ["cooking-greens"],
    perPerson: 1.5,
    yield: "One main head plus weeks of side shoots",
    varieties: ["Green Magic", "Packman", "Di Cicco"],
    tips: [
      "Cut the main head while the buds are tight, before any yellow flowers show.",
      "After the main head, side shoots keep coming for weeks.",
      "Often better as a fall crop. Heads form best in cool weather.",
    ],
    seedCost: 3.5,
    startCost: 4.5,
  }),
  plant({
    id: "cabbage",
    name: "Cabbage",
    emoji: "🥬",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "full",
    perSqFt: 1,
    heightIn: 18,
    pot: { gal: 5, plants: 1 },
    dtm: 70,
    harvestWeeks: 3,
    method: "transplant",
    indoorWeeks: 8,
    plantOutWeeks: -3,
    fall: true,
    buyStarts: true,
    difficulty: 2,
    water: "medium",
    feeder: "heavy",
    companions: ["dill", "scallions", "beet", "swiss-chard", "nasturtium", "thyme", "sage"],
    avoid: ["strawberry", "tomato", "cherry-tomato", "paste-tomato"],
    goals: ["preserving", "cooking-greens"],
    perPerson: 1,
    yield: "One 2–4 lb head per plant",
    varieties: ["Golden Acre", "Copenhagen Market", "Red Express"],
    tips: [
      "Harvest when the head feels firm and solid when squeezed.",
      "Uneven watering makes heads split, so keep moisture consistent.",
      "Row cover keeps cabbage moths from laying eggs on young plants.",
    ],
    seedCost: 3.5,
    startCost: 4.5,
  }),
  plant({
    id: "bok-choy",
    name: "Bok choy",
    emoji: "🥬",
    category: "vegetable",
    season: "cool",
    frost: "half-hardy",
    sun: "partial",
    perSqFt: 4,
    heightIn: 12,
    pot: { gal: 2, plants: 1 },
    dtm: 45,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: -4,
    fall: true,
    succession: 3,
    difficulty: 1,
    water: "high",
    feeder: "medium",
    companions: ["lettuce", "dill", "scallions", "beet"],
    avoid: ["strawberry"],
    goals: ["cooking-greens"],
    perPerson: 2,
    yield: "Full heads in about 6 weeks",
    varieties: ["Joi Choi", "Toy Choy", "Win-Win"],
    tips: [
      "Bolts in heat and long days. Best in spring and fall.",
      "Harvest baby leaves at 4 weeks or the whole head at full size.",
      "Row cover keeps flea beetles off the leaves.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "scallions",
    name: "Green onions",
    emoji: "🧅",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 16,
    heightIn: 12,
    pot: { gal: 1, plants: 8 },
    dtm: 60,
    harvestWeeks: 8,
    method: "direct",
    plantOutWeeks: -4,
    fall: true,
    succession: 4,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["carrot", "tomato", "bell-pepper", "hot-pepper", "lettuce", "beet", "kale", "cabbage", "swiss-chard"],
    avoid: ["bush-beans", "pole-beans", "snap-peas"],
    goals: ["salad", "salsa"],
    perPerson: 8,
    yield: "Pull as needed for months",
    varieties: ["Evergreen Hardy White", "Tokyo Long White", "Red Beard"],
    tips: [
      "Snip the tops and they regrow, or pull the whole plant.",
      "Tuck them into gaps between other crops; they take almost no space.",
      "Bulb onions need a long season. Green onions are the easy beginner version.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "garlic",
    name: "Garlic",
    emoji: "🧄",
    category: "vegetable",
    season: "cool",
    frost: "hardy",
    sun: "full",
    perSqFt: 9,
    heightIn: 24,
    pot: { gal: 3, plants: 4 },
    dtm: 240,
    harvestWeeks: 2,
    method: "direct",
    plantOutWeeks: 0,
    overwinter: true,
    buyStarts: true,
    difficulty: 1,
    water: "low",
    feeder: "medium",
    companions: ["tomato", "carrot", "beet", "lettuce", "strawberry", "kale"],
    avoid: ["bush-beans", "pole-beans", "snap-peas"],
    goals: ["low-maintenance", "pizza", "salsa", "preserving"],
    perPerson: 9,
    yield: "One head per clove planted; stores 6+ months",
    varieties: ["Music (hardneck)", "California Early (softneck)", "German Extra Hardy"],
    tips: [
      "Plant individual cloves pointy-end up, 2 inches deep, in fall.",
      "Mulch heavily after planting. It overwinters and takes off in spring.",
      "Snap off the curly 'scapes' in early summer (they're delicious) for bigger bulbs.",
    ],
    seedCost: 3,
    startCost: 3,
  }),
  plant({
    id: "potato",
    name: "Potato",
    emoji: "🥔",
    category: "vegetable",
    season: "cool",
    frost: "half-hardy",
    sun: "full",
    perSqFt: 1,
    heightIn: 24,
    pot: { gal: 10, plants: 2 },
    dtm: 90,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: -2,
    buyStarts: true,
    difficulty: 1,
    water: "medium",
    feeder: "medium",
    companions: ["bush-beans", "cabbage", "marigold", "kale"],
    avoid: ["tomato", "cherry-tomato", "paste-tomato", "cucumber", "winter-squash", "zucchini", "pumpkin", "sunflower", "eggplant"],
    goals: ["kids", "preserving"],
    perPerson: 3,
    yield: "3–5 lb per plant",
    varieties: ["Yukon Gold", "Red Pontiac", "Kennebec"],
    tips: [
      "Use certified seed potatoes. Grocery potatoes are often treated to stop sprouting.",
      "'Hill' soil or mulch around the stems as they grow so tubers stay covered; sun turns them green.",
      "Dig 'new' potatoes at flowering, full-size ones after the vines die back.",
    ],
    seedCost: 4,
    startCost: 4,
  }),

  // ---------- Herbs ----------
  plant({
    id: "basil",
    name: "Basil",
    emoji: "🌿",
    category: "herb",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 4,
    heightIn: 18,
    pot: { gal: 1, plants: 1 },
    dtm: 30,
    harvestWeeks: 12,
    method: "transplant",
    indoorWeeks: 6,
    plantOutWeeks: 2,
    buyStarts: true,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["tomato", "cherry-tomato", "paste-tomato", "bell-pepper", "hot-pepper", "eggplant", "marigold", "oregano"],
    avoid: ["sage"],
    goals: ["herbs", "pizza", "salad"],
    perPerson: 2,
    yield: "A big handful every week",
    varieties: ["Genovese", "Thai", "Spicy Globe"],
    tips: [
      "Pinch off flower buds and the top pair of leaves often to keep it bushy.",
      "Very frost-sensitive. Wait until nights stay above 50°F.",
      "Harvest from the top down, just above a pair of leaves.",
    ],
    seedCost: 3.5,
    startCost: 4,
  }),
  plant({
    id: "parsley",
    name: "Parsley",
    emoji: "🌿",
    category: "herb",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 4,
    heightIn: 12,
    pot: { gal: 1, plants: 1 },
    dtm: 30,
    harvestWeeks: 20,
    method: "transplant",
    indoorWeeks: 10,
    plantOutWeeks: -2,
    fall: true,
    buyStarts: true,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["tomato", "cherry-tomato", "chives", "bell-pepper"],
    goals: ["herbs", "salad", "pollinators"],
    perPerson: 1,
    yield: "Steady harvests from spring to fall",
    varieties: ["Italian Flat Leaf", "Moss Curled"],
    tips: [
      "Cut outer stems at the base and leave the center to keep growing.",
      "Swallowtail caterpillars love parsley. Plant a little extra to share with butterflies.",
      "It's a biennial: it often survives winter and flowers the next spring.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "cilantro",
    name: "Cilantro",
    emoji: "🌿",
    category: "herb",
    season: "cool",
    frost: "half-hardy",
    sun: "partial",
    perSqFt: 9,
    heightIn: 18,
    pot: { gal: 1, plants: 3 },
    dtm: 45,
    harvestWeeks: 4,
    method: "direct",
    plantOutWeeks: -2,
    fall: true,
    succession: 3,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["tomato", "bell-pepper", "hot-pepper", "spinach", "lettuce"],
    goals: ["salsa", "herbs"],
    perPerson: 3,
    yield: "Fresh leaves for about a month per sowing",
    varieties: ["Calypso", "Santo", "Leisure"],
    tips: [
      "Bolts quickly in heat. Sow small batches every 3 weeks in spring and fall.",
      "Let a few plants flower: the blooms feed beneficial insects and the seeds are coriander.",
      "Afternoon shade extends the harvest.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "dill",
    name: "Dill",
    emoji: "🌿",
    category: "herb",
    season: "cool",
    frost: "half-hardy",
    sun: "full",
    perSqFt: 1,
    heightIn: 36,
    pot: { gal: 2, plants: 1 },
    dtm: 45,
    harvestWeeks: 6,
    method: "direct",
    plantOutWeeks: 0,
    fall: true,
    succession: 4,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["cucumber", "cabbage", "broccoli", "lettuce", "scallions", "kale"],
    avoid: ["carrot", "tomato", "cherry-tomato", "paste-tomato"],
    goals: ["herbs", "pollinators", "preserving"],
    perPerson: 1,
    yield: "Fronds all summer, seed heads for pickling",
    varieties: ["Bouquet", "Fernleaf", "Mammoth"],
    tips: [
      "Direct sow. Dill hates being transplanted.",
      "Its flowers attract ladybugs and other aphid-eating insects.",
      "Black swallowtail caterpillars feed on dill; plant extra if you want butterflies.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "chives",
    name: "Chives",
    emoji: "🌿",
    category: "herb",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 4,
    heightIn: 12,
    pot: { gal: 1, plants: 1 },
    dtm: 30,
    harvestWeeks: 20,
    method: "transplant",
    indoorWeeks: 8,
    plantOutWeeks: -3,
    buyStarts: true,
    perennial: true,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["carrot", "tomato", "cherry-tomato", "strawberry", "lettuce", "broccoli"],
    avoid: ["bush-beans", "pole-beans", "snap-peas"],
    goals: ["herbs", "pollinators", "low-maintenance"],
    perPerson: 0.5,
    yield: "Regrows after every cutting",
    varieties: ["Common chives", "Garlic chives"],
    tips: [
      "A perennial that returns every year. Give it a permanent corner.",
      "Cut to 2 inches above the soil and it regrows in a few weeks.",
      "The purple flowers are edible and bees love them.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "mint",
    name: "Mint",
    emoji: "🌿",
    category: "herb",
    season: "cool",
    frost: "hardy",
    sun: "partial",
    perSqFt: 1,
    heightIn: 18,
    pot: { gal: 2, plants: 1 },
    dtm: 30,
    harvestWeeks: 20,
    method: "transplant",
    plantOutWeeks: 0,
    buyStarts: true,
    perennial: true,
    difficulty: 1,
    water: "medium",
    feeder: "light",
    companions: ["cabbage", "tomato", "snap-peas"],
    goals: ["herbs", "low-maintenance", "kids"],
    perPerson: 0.34,
    yield: "More than you'll ever use",
    varieties: ["Spearmint", "Peppermint", "Mojito mint"],
    tips: [
      "Extremely invasive. Always grow mint in a pot (you can sink the pot into the bed).",
      "Cut back hard in midsummer for a fresh flush of leaves.",
      "Comes back every year.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "oregano",
    name: "Oregano",
    emoji: "🌿",
    category: "herb",
    season: "warm",
    frost: "hardy",
    sun: "full",
    perSqFt: 1,
    heightIn: 18,
    pot: { gal: 1, plants: 1 },
    dtm: 40,
    harvestWeeks: 20,
    method: "transplant",
    plantOutWeeks: 0,
    buyStarts: true,
    perennial: true,
    difficulty: 1,
    water: "low",
    feeder: "light",
    companions: ["tomato", "bell-pepper", "basil", "cucumber"],
    goals: ["herbs", "pizza", "low-maintenance", "pollinators"],
    perPerson: 0.34,
    yield: "Plenty for fresh use and drying",
    varieties: ["Greek oregano", "Italian oregano"],
    tips: [
      "Thrives on neglect: lean soil and little water give the most flavor.",
      "Flavor peaks just before it flowers.",
      "Perennial in zones 5–10. Trim it back in early spring.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "thyme",
    name: "Thyme",
    emoji: "🌿",
    category: "herb",
    season: "warm",
    frost: "hardy",
    sun: "full",
    perSqFt: 4,
    heightIn: 10,
    pot: { gal: 1, plants: 1 },
    dtm: 40,
    harvestWeeks: 20,
    method: "transplant",
    plantOutWeeks: 0,
    buyStarts: true,
    perennial: true,
    difficulty: 1,
    water: "low",
    feeder: "light",
    companions: ["cabbage", "tomato", "strawberry", "eggplant"],
    goals: ["herbs", "low-maintenance", "pollinators"],
    perPerson: 0.34,
    yield: "Snip sprigs all season",
    varieties: ["English thyme", "Lemon thyme"],
    tips: [
      "Needs sharp drainage. Great along the sunny edge of a bed or in a pot.",
      "Trim lightly after flowering to keep it from getting woody.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "rosemary",
    name: "Rosemary",
    emoji: "🌿",
    category: "herb",
    season: "warm",
    frost: "half-hardy",
    sun: "full",
    perSqFt: 1,
    heightIn: 36,
    pot: { gal: 3, plants: 1 },
    dtm: 60,
    harvestWeeks: 20,
    method: "transplant",
    plantOutWeeks: 1,
    buyStarts: true,
    perennial: true,
    difficulty: 2,
    water: "low",
    feeder: "light",
    companions: ["cabbage", "bush-beans", "carrot", "sage"],
    goals: ["herbs", "low-maintenance", "pollinators"],
    perPerson: 0.34,
    yield: "Sprigs year-round in mild climates",
    varieties: ["Arp (cold-hardy)", "Tuscan Blue"],
    tips: [
      "Overwinters outdoors in zone 7 and warmer. Elsewhere grow it in a pot and bring it inside.",
      "Let the soil dry between waterings; soggy roots kill rosemary.",
    ],
    seedCost: 3,
    startCost: 5,
  }),
  plant({
    id: "sage",
    name: "Sage",
    emoji: "🌿",
    category: "herb",
    season: "warm",
    frost: "hardy",
    sun: "full",
    perSqFt: 1,
    heightIn: 24,
    pot: { gal: 2, plants: 1 },
    dtm: 50,
    harvestWeeks: 20,
    method: "transplant",
    plantOutWeeks: 0,
    buyStarts: true,
    perennial: true,
    difficulty: 1,
    water: "low",
    feeder: "light",
    companions: ["rosemary", "cabbage", "carrot", "strawberry"],
    avoid: ["cucumber", "basil"],
    goals: ["herbs", "pollinators", "low-maintenance"],
    perPerson: 0.34,
    yield: "Leaves all season; perennial in zones 5–8",
    varieties: ["Common sage", "Berggarten"],
    tips: [
      "Drought tolerant once established. Don't overwater.",
      "Prune woody stems in spring to keep it bushy.",
    ],
    seedCost: 3,
    startCost: 4,
  }),

  // ---------- Flowers ----------
  plant({
    id: "marigold",
    name: "Marigold",
    emoji: "🌼",
    category: "flower",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 4,
    heightIn: 12,
    pot: { gal: 1, plants: 1 },
    dtm: 30,
    harvestWeeks: 16,
    method: "transplant",
    indoorWeeks: 6,
    plantOutWeeks: 1,
    buyStarts: true,
    difficulty: 1,
    water: "low",
    feeder: "light",
    companions: ["tomato", "cherry-tomato", "paste-tomato", "bell-pepper", "eggplant", "cucumber", "zucchini", "winter-squash", "bush-beans", "potato"],
    goals: ["pollinators", "kids", "low-maintenance"],
    perPerson: 2,
    yield: "Blooms from early summer to frost",
    varieties: ["Petite French", "Durango", "Crackerjack"],
    tips: [
      "Tuck them along bed edges: bright color, and a magnet for pollinators and hoverflies.",
      "French marigolds can help suppress root-knot nematodes in the soil.",
      "Deadhead spent blooms to keep flowers coming.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "nasturtium",
    name: "Nasturtium",
    emoji: "🌺",
    category: "flower",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1,
    heightIn: 12,
    pot: { gal: 1, plants: 1 },
    dtm: 50,
    harvestWeeks: 14,
    method: "direct",
    plantOutWeeks: 1,
    difficulty: 1,
    water: "low",
    feeder: "light",
    companions: ["cucumber", "zucchini", "winter-squash", "tomato", "broccoli", "cabbage", "kale", "cantaloupe", "watermelon"],
    goals: ["pollinators", "kids", "salad", "low-maintenance"],
    perPerson: 1,
    yield: "Peppery edible flowers and leaves all summer",
    varieties: ["Jewel Mix", "Alaska", "Empress of India"],
    tips: [
      "Leaves and flowers are edible with a peppery bite. Great in salads.",
      "Works as a 'trap crop': aphids go for nasturtiums instead of your vegetables.",
      "Don't fertilize. Rich soil means lots of leaves and few flowers.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "zinnia",
    name: "Zinnia",
    emoji: "🌸",
    category: "flower",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1,
    heightIn: 30,
    pot: { gal: 2, plants: 1 },
    dtm: 60,
    harvestWeeks: 12,
    method: "direct",
    plantOutWeeks: 1,
    difficulty: 1,
    water: "low",
    feeder: "light",
    companions: ["tomato", "bell-pepper", "cucumber", "zucchini"],
    goals: ["pollinators", "kids", "low-maintenance"],
    perPerson: 1,
    yield: "Armloads of cut flowers",
    varieties: ["State Fair", "Zahara", "Benary's Giant"],
    tips: [
      "Cut flowers often. The more you cut, the more they bloom.",
      "Butterflies love them; plant near squash and cucumbers to boost pollination.",
      "Water at the base to avoid powdery mildew.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "sunflower",
    name: "Sunflower",
    emoji: "🌻",
    category: "flower",
    season: "warm",
    frost: "tender",
    sun: "full",
    perSqFt: 1,
    heightIn: 72,
    pot: { gal: 5, plants: 1 },
    dtm: 75,
    harvestWeeks: 3,
    method: "direct",
    plantOutWeeks: 1,
    difficulty: 1,
    water: "medium",
    feeder: "medium",
    companions: ["cucumber", "sweet-corn", "zucchini"],
    avoid: ["potato"],
    goals: ["kids", "pollinators"],
    perPerson: 1,
    yield: "Huge blooms, then seeds for you or the birds",
    varieties: ["Teddy Bear", "Autumn Beauty", "Mammoth"],
    tips: [
      "Plant on the north side; tall sunflowers shade everything behind them.",
      "Kids love giant varieties. Measure them every week!",
      "Leave some heads standing in fall for the birds.",
    ],
    seedCost: 3,
    startCost: 4,
  }),
  plant({
    id: "calendula",
    name: "Calendula",
    emoji: "🌼",
    category: "flower",
    season: "cool",
    frost: "half-hardy",
    sun: "full",
    perSqFt: 4,
    heightIn: 18,
    pot: { gal: 1, plants: 1 },
    dtm: 50,
    harvestWeeks: 12,
    method: "direct",
    plantOutWeeks: -2,
    fall: true,
    difficulty: 1,
    water: "low",
    feeder: "light",
    companions: ["tomato", "lettuce", "kale", "broccoli", "cabbage", "cucumber"],
    goals: ["pollinators", "salad", "low-maintenance"],
    perPerson: 1,
    yield: "Cheerful blooms in spring and fall",
    varieties: ["Pacific Beauty", "Resina", "Zeolights"],
    tips: [
      "Edible petals add color to salads.",
      "Tolerates light frost, so it blooms in spring and fall when other flowers quit.",
      "Deadhead to keep it flowering.",
    ],
    seedCost: 3,
    startCost: 4,
  }),

  // ---------- Fruit ----------
  plant({
    id: "strawberry",
    name: "Strawberry",
    emoji: "🍓",
    category: "fruit",
    season: "cool",
    frost: "hardy",
    sun: "full",
    perSqFt: 1,
    heightIn: 8,
    pot: { gal: 1, plants: 1 },
    dtm: 60,
    harvestWeeks: 8,
    method: "transplant",
    plantOutWeeks: -3,
    buyStarts: true,
    perennial: true,
    difficulty: 2,
    water: "medium",
    feeder: "medium",
    companions: ["spinach", "lettuce", "bush-beans", "chives", "thyme"],
    avoid: ["cabbage", "broccoli", "kale", "bok-choy"],
    goals: ["kids", "preserving"],
    perPerson: 4,
    yield: "About a quart per plant per season once established",
    varieties: ["Albion (everbearing)", "Seascape (day-neutral)", "Earliglow (June-bearing)"],
    tips: [
      "Day-neutral or everbearing types fruit the first year; June-bearers mostly the second.",
      "Pinch off runners to keep plants productive (or root them for new plants).",
      "Mulch with straw to keep berries clean and off the soil.",
    ],
    seedCost: 4,
    startCost: 2,
  }),
];

export const PLANTS_BY_ID: Record<string, Plant> = Object.fromEntries(PLANTS.map((p) => [p.id, p]));

export function getPlant(id: string): Plant {
  const p = PLANTS_BY_ID[id];
  if (!p) throw new Error(`Unknown plant: ${id}`);
  return p;
}

/** Tile colors for the layout grid. */
export const PLANT_COLORS: Record<string, string> = {
  tomato: "#d93f3f",
  "cherry-tomato": "#f2711c",
  "paste-tomato": "#b02a37",
  "bell-pepper": "#3f9b4a",
  "hot-pepper": "#c8322b",
  eggplant: "#7b4fb3",
  cucumber: "#2e8b57",
  zucchini: "#4c7a34",
  "winter-squash": "#e39b2d",
  pumpkin: "#ee7a1a",
  cantaloupe: "#f2b260",
  watermelon: "#e2526b",
  "bush-beans": "#5aa96f",
  "pole-beans": "#3c8d55",
  "sweet-corn": "#e9b829",
  okra: "#7a9b45",
  lettuce: "#8cc152",
  spinach: "#2f7a3c",
  kale: "#355e44",
  "swiss-chard": "#c43d7b",
  arugula: "#6a9f4b",
  radish: "#d9466f",
  carrot: "#ef7d22",
  beet: "#8e2350",
  "snap-peas": "#6aab2e",
  broccoli: "#2b6a3b",
  cabbage: "#9bbf63",
  "bok-choy": "#58b368",
  scallions: "#97b84a",
  garlic: "#b9ad9b",
  potato: "#a7783f",
  basil: "#2fa35a",
  parsley: "#1f7a3a",
  cilantro: "#5c8a2e",
  dill: "#8fa86b",
  chives: "#9a7bd1",
  mint: "#35b58b",
  oregano: "#6b8e3a",
  thyme: "#7f9c86",
  rosemary: "#4f7a6c",
  sage: "#8d9caa",
  marigold: "#f0a422",
  nasturtium: "#f2803a",
  zinnia: "#e04e98",
  sunflower: "#f2c318",
  calendula: "#f4b330",
  strawberry: "#e23c3c",
};

/** Short two-letter labels for layout tiles. */
export const PLANT_ABBR: Record<string, string> = {
  tomato: "To",
  "cherry-tomato": "Ct",
  "paste-tomato": "Pt",
  "bell-pepper": "Bp",
  "hot-pepper": "Hp",
  eggplant: "Eg",
  cucumber: "Cu",
  zucchini: "Zu",
  "winter-squash": "Ws",
  pumpkin: "Pu",
  cantaloupe: "Ca",
  watermelon: "Wm",
  "bush-beans": "Bb",
  "pole-beans": "Pb",
  "sweet-corn": "Co",
  okra: "Ok",
  lettuce: "Le",
  spinach: "Sp",
  kale: "Ka",
  "swiss-chard": "Ch",
  arugula: "Ar",
  radish: "Ra",
  carrot: "Cr",
  beet: "Be",
  "snap-peas": "Pe",
  broccoli: "Br",
  cabbage: "Cb",
  "bok-choy": "Bk",
  scallions: "On",
  garlic: "Ga",
  potato: "Po",
  basil: "Ba",
  parsley: "Pa",
  cilantro: "Ci",
  dill: "Di",
  chives: "Cv",
  mint: "Mi",
  oregano: "Or",
  thyme: "Th",
  rosemary: "Ro",
  sage: "Sa",
  marigold: "Ma",
  nasturtium: "Na",
  zinnia: "Zi",
  sunflower: "Su",
  calendula: "Cl",
  strawberry: "St",
};

export const GOALS: { id: Goal; label: string; emoji: string; blurb: string }[] = [
  { id: "salad", label: "Salad garden", emoji: "🥗", blurb: "Lettuce, greens, cukes, radishes" },
  { id: "salsa", label: "Salsa garden", emoji: "🌶️", blurb: "Tomatoes, peppers, cilantro" },
  { id: "herbs", label: "Kitchen herbs", emoji: "🌿", blurb: "Basil, parsley, thyme & more" },
  { id: "pizza", label: "Pizza garden", emoji: "🍕", blurb: "Tomatoes, basil, oregano, peppers" },
  { id: "pollinators", label: "Pollinator friendly", emoji: "🐝", blurb: "Flowers that bring the bees" },
  { id: "kids", label: "Fun with kids", emoji: "🧒", blurb: "Fast, sweet and easy to pick" },
  { id: "cooking-greens", label: "Cooking greens", emoji: "🥬", blurb: "Kale, chard, spinach, broccoli" },
  { id: "preserving", label: "Canning & storing", emoji: "🫙", blurb: "Sauce tomatoes, beans, squash" },
  { id: "low-maintenance", label: "Low maintenance", emoji: "😌", blurb: "Forgiving, set-and-forget picks" },
];

/** Plant spacing expressed for humans, e.g. "4 per sq ft" or "1 per 2×2 ft". */
export function spacingLabel(p: Plant): string {
  if (p.perSqFt >= 1) return `${p.perSqFt} per sq ft`;
  const side = Math.round(Math.sqrt(1 / p.perSqFt));
  return `1 per ${side}×${side} ft`;
}
